# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/system_cons.xdc

# IP: ip/dec_fifo_8w_8r/dec_fifo_8w_8r.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dec_fifo_8w_8r || ORIG_REF_NAME==dec_fifo_8w_8r} -quiet] -quiet

# IP: ip/rs_decoder_0/rs_decoder_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rs_decoder_0 || ORIG_REF_NAME==rs_decoder_0} -quiet] -quiet

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/design_1_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==design_1_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_fso_rx_top_0_0/design_1_fso_rx_top_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_fso_rx_top_0_0 || ORIG_REF_NAME==design_1_fso_rx_top_0_0} -quiet] -quiet

# IP: ip/dec_rx_fifo/dec_rx_fifo.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dec_rx_fifo || ORIG_REF_NAME==dec_rx_fifo} -quiet] -quiet

# IP: ip/async_fifo_32w_32r/async_fifo_32w_32r.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==async_fifo_32w_32r || ORIG_REF_NAME==async_fifo_32w_32r} -quiet] -quiet

# IP: ip/gtwizard_ultrascale_0/gtwizard_ultrascale_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==gtwizard_ultrascale_0 || ORIG_REF_NAME==gtwizard_ultrascale_0} -quiet] -quiet

# IP: ip/clk_wiz_0/clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet

# IP: ip/dec_fifo_8w_8r/dec_fifo_8w_8r.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dec_fifo_8w_8r || ORIG_REF_NAME==dec_fifo_8w_8r} -quiet] -quiet

# IP: ip/rs_decoder_0/rs_decoder_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rs_decoder_0 || ORIG_REF_NAME==rs_decoder_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_smc_2/design_1_axi_smc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_smc_2 || ORIG_REF_NAME==design_1_axi_smc_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_ps8_0_100M_1/design_1_rst_ps8_0_100M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_rst_ps8_0_100M_1 || ORIG_REF_NAME==design_1_rst_ps8_0_100M_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ila_0_0/design_1_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ila_0_0 || ORIG_REF_NAME==design_1_ila_0_0} -quiet] -quiet

# XDC: c:/Users/PC/Desktop/fps/EnDec/project_1/project_1.gen/sources_1/bd/design_1/design_1_ooc.xdc
