######################################################################
#
# File name : loopback_tb_compile.do
# Created on: Mon Oct 27 20:06:00 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
C:\\modeltech64_2020.4\\win64\\vlib modelsim_lib/work
C:\\modeltech64_2020.4\\win64\\vlib modelsim_lib/msim

C:\\modeltech64_2020.4\\win64\\vlib modelsim_lib/msim/xilinx_vip
C:\\modeltech64_2020.4\\win64\\vlib modelsim_lib/msim/xpm
C:\\modeltech64_2020.4\\win64\\vlib modelsim_lib/msim/xbip_utils_v3_0_14
C:\\modeltech64_2020.4\\win64\\vlib modelsim_lib/msim/axi_utils_v2_0_10
C:\\modeltech64_2020.4\\win64\\vlib modelsim_lib/msim/c_reg_fd_v12_0_10
C:\\modeltech64_2020.4\\win64\\vlib modelsim_lib/msim/xbip_dsp48_wrapper_v3_0_6
C:\\modeltech64_2020.4\\win64\\vlib modelsim_lib/msim/xbip_pipe_v3_0_10
C:\\modeltech64_2020.4\\win64\\vlib modelsim_lib/msim/c_addsub_v12_0_19
C:\\modeltech64_2020.4\\win64\\vlib modelsim_lib/msim/c_compare_v12_0_10
C:\\modeltech64_2020.4\\win64\\vlib modelsim_lib/msim/c_counter_binary_v12_0_20
C:\\modeltech64_2020.4\\win64\\vlib modelsim_lib/msim/c_shift_ram_v12_0_18
C:\\modeltech64_2020.4\\win64\\vlib modelsim_lib/msim/mult_gen_v12_0_22
C:\\modeltech64_2020.4\\win64\\vlib modelsim_lib/msim/rs_toolbox_v9_0_14
C:\\modeltech64_2020.4\\win64\\vlib modelsim_lib/msim/sid_v8_0_22
C:\\modeltech64_2020.4\\win64\\vlib modelsim_lib/msim/xil_defaultlib
C:\\modeltech64_2020.4\\win64\\vlib modelsim_lib/msim/rs_encoder_v9_0_22
C:\\modeltech64_2020.4\\win64\\vlib modelsim_lib/msim/fifo_generator_v13_2_11

C:\\modeltech64_2020.4\\win64\\vmap xilinx_vip modelsim_lib/msim/xilinx_vip
C:\\modeltech64_2020.4\\win64\\vmap xpm modelsim_lib/msim/xpm
C:\\modeltech64_2020.4\\win64\\vmap xbip_utils_v3_0_14 modelsim_lib/msim/xbip_utils_v3_0_14
C:\\modeltech64_2020.4\\win64\\vmap axi_utils_v2_0_10 modelsim_lib/msim/axi_utils_v2_0_10
C:\\modeltech64_2020.4\\win64\\vmap c_reg_fd_v12_0_10 modelsim_lib/msim/c_reg_fd_v12_0_10
C:\\modeltech64_2020.4\\win64\\vmap xbip_dsp48_wrapper_v3_0_6 modelsim_lib/msim/xbip_dsp48_wrapper_v3_0_6
C:\\modeltech64_2020.4\\win64\\vmap xbip_pipe_v3_0_10 modelsim_lib/msim/xbip_pipe_v3_0_10
C:\\modeltech64_2020.4\\win64\\vmap c_addsub_v12_0_19 modelsim_lib/msim/c_addsub_v12_0_19
C:\\modeltech64_2020.4\\win64\\vmap c_compare_v12_0_10 modelsim_lib/msim/c_compare_v12_0_10
C:\\modeltech64_2020.4\\win64\\vmap c_counter_binary_v12_0_20 modelsim_lib/msim/c_counter_binary_v12_0_20
C:\\modeltech64_2020.4\\win64\\vmap c_shift_ram_v12_0_18 modelsim_lib/msim/c_shift_ram_v12_0_18
C:\\modeltech64_2020.4\\win64\\vmap mult_gen_v12_0_22 modelsim_lib/msim/mult_gen_v12_0_22
C:\\modeltech64_2020.4\\win64\\vmap rs_toolbox_v9_0_14 modelsim_lib/msim/rs_toolbox_v9_0_14
C:\\modeltech64_2020.4\\win64\\vmap sid_v8_0_22 modelsim_lib/msim/sid_v8_0_22
C:\\modeltech64_2020.4\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib
C:\\modeltech64_2020.4\\win64\\vmap rs_encoder_v9_0_22 modelsim_lib/msim/rs_encoder_v9_0_22
C:\\modeltech64_2020.4\\win64\\vmap fifo_generator_v13_2_11 modelsim_lib/msim/fifo_generator_v13_2_11

C:\\modeltech64_2020.4\\win64\\vlog  -mfcu -sv -L axi_vip_v1_1_19 -L smartconnect_v1_0 -L zynq_ultra_ps_e_vip_v1_0_19 -L xilinx_vip -work xilinx_vip  "+incdir+D:/2024_2/Vivado/2024.2/data/xilinx_vip/include" \
"D:/2024_2/Vivado/2024.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
"D:/2024_2/Vivado/2024.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
"D:/2024_2/Vivado/2024.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
"D:/2024_2/Vivado/2024.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
"D:/2024_2/Vivado/2024.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
"D:/2024_2/Vivado/2024.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
"D:/2024_2/Vivado/2024.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
"D:/2024_2/Vivado/2024.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
"D:/2024_2/Vivado/2024.2/data/xilinx_vip/hdl/rst_vip_if.sv" \

C:\\modeltech64_2020.4\\win64\\vlog  -mfcu -sv -L axi_vip_v1_1_19 -L smartconnect_v1_0 -L zynq_ultra_ps_e_vip_v1_0_19 -L xilinx_vip -work xpm  "+incdir+../../../../project_1.gen/sources_1/ip/ddr4_0/ip_1/rtl/map" "+incdir+../../../../project_1.gen/sources_1/ip/ddr4_0/rtl/ip_top" "+incdir+../../../../project_1.gen/sources_1/ip/ddr4_0/rtl/cal" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/6f8f/hdl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/0127/hdl/verilog" "+incdir+D:/2024_2/Vivado/2024.2/data/xilinx_vip/include" \
"D:/2024_2/Vivado/2024.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
"D:/2024_2/Vivado/2024.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \

C:\\modeltech64_2020.4\\win64\\vcom  -93 -work xpm  \
"D:/2024_2/Vivado/2024.2/data/ip/xpm/xpm_VCOMP.vhd" \

C:\\modeltech64_2020.4\\win64\\vcom  -93 -work xbip_utils_v3_0_14  \
"../../../../project_1.ip_user_files/ipstatic/hdl/xbip_utils_v3_0_vh_rfs.vhd" \

C:\\modeltech64_2020.4\\win64\\vcom  -93 -work axi_utils_v2_0_10  \
"../../../../project_1.ip_user_files/ipstatic/hdl/axi_utils_v2_0_vh_rfs.vhd" \

C:\\modeltech64_2020.4\\win64\\vcom  -93 -work c_reg_fd_v12_0_10  \
"../../../../project_1.ip_user_files/ipstatic/hdl/c_reg_fd_v12_0_vh_rfs.vhd" \

C:\\modeltech64_2020.4\\win64\\vcom  -93 -work xbip_dsp48_wrapper_v3_0_6  \
"../../../../project_1.ip_user_files/ipstatic/hdl/xbip_dsp48_wrapper_v3_0_vh_rfs.vhd" \

C:\\modeltech64_2020.4\\win64\\vcom  -93 -work xbip_pipe_v3_0_10  \
"../../../../project_1.ip_user_files/ipstatic/hdl/xbip_pipe_v3_0_vh_rfs.vhd" \

C:\\modeltech64_2020.4\\win64\\vcom  -93 -work c_addsub_v12_0_19  \
"../../../../project_1.ip_user_files/ipstatic/hdl/c_addsub_v12_0_vh_rfs.vhd" \

C:\\modeltech64_2020.4\\win64\\vcom  -93 -work c_compare_v12_0_10  \
"../../../../project_1.ip_user_files/ipstatic/hdl/c_compare_v12_0_vh_rfs.vhd" \

C:\\modeltech64_2020.4\\win64\\vcom  -93 -work c_counter_binary_v12_0_20  \
"../../../../project_1.ip_user_files/ipstatic/hdl/c_counter_binary_v12_0_vh_rfs.vhd" \

C:\\modeltech64_2020.4\\win64\\vcom  -93 -work c_shift_ram_v12_0_18  \
"../../../../project_1.ip_user_files/ipstatic/hdl/c_shift_ram_v12_0_vh_rfs.vhd" \

C:\\modeltech64_2020.4\\win64\\vcom  -93 -work mult_gen_v12_0_22  \
"../../../../project_1.ip_user_files/ipstatic/hdl/mult_gen_v12_0_vh_rfs.vhd" \

C:\\modeltech64_2020.4\\win64\\vcom  -93 -work rs_toolbox_v9_0_14  \
"../../../../project_1.ip_user_files/ipstatic/hdl/rs_toolbox_v9_0_vh_rfs.vhd" \

C:\\modeltech64_2020.4\\win64\\vcom  -93 -work sid_v8_0_22  \
"../../../../project_1.ip_user_files/ipstatic/hdl/sid_v8_0_vh_rfs.vhd" \

C:\\modeltech64_2020.4\\win64\\vcom  -93 -work xil_defaultlib  \
"../../../../project_1.gen/sources_1/ip/sid_0/sim/sid_0.vhd" \

C:\\modeltech64_2020.4\\win64\\vcom  -93 -work rs_encoder_v9_0_22  \
"../../../../project_1.ip_user_files/ipstatic/hdl/rs_encoder_v9_0_vh_rfs.vhd" \

C:\\modeltech64_2020.4\\win64\\vcom  -93 -work xil_defaultlib  \
"../../../../project_1.gen/sources_1/ip/rs_encoder_0/sim/rs_encoder_0.vhd" \

C:\\modeltech64_2020.4\\win64\\vlog  -mfcu -work fifo_generator_v13_2_11  "+incdir+../../../../project_1.gen/sources_1/ip/ddr4_0/ip_1/rtl/map" "+incdir+../../../../project_1.gen/sources_1/ip/ddr4_0/rtl/ip_top" "+incdir+../../../../project_1.gen/sources_1/ip/ddr4_0/rtl/cal" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/6f8f/hdl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/0127/hdl/verilog" "+incdir+D:/2024_2/Vivado/2024.2/data/xilinx_vip/include" \
"../../../../project_1.ip_user_files/ipstatic/simulation/fifo_generator_vlog_beh.v" \

C:\\modeltech64_2020.4\\win64\\vcom  -93 -work fifo_generator_v13_2_11  \
"../../../../project_1.ip_user_files/ipstatic/hdl/fifo_generator_v13_2_rfs.vhd" \

C:\\modeltech64_2020.4\\win64\\vlog  -mfcu -work fifo_generator_v13_2_11  "+incdir+../../../../project_1.gen/sources_1/ip/ddr4_0/ip_1/rtl/map" "+incdir+../../../../project_1.gen/sources_1/ip/ddr4_0/rtl/ip_top" "+incdir+../../../../project_1.gen/sources_1/ip/ddr4_0/rtl/cal" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/6f8f/hdl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/0127/hdl/verilog" "+incdir+D:/2024_2/Vivado/2024.2/data/xilinx_vip/include" \
"../../../../project_1.ip_user_files/ipstatic/hdl/fifo_generator_v13_2_rfs.v" \

C:\\modeltech64_2020.4\\win64\\vlog  -mfcu -work xil_defaultlib  "+incdir+../../../../project_1.gen/sources_1/ip/ddr4_0/ip_1/rtl/map" "+incdir+../../../../project_1.gen/sources_1/ip/ddr4_0/rtl/ip_top" "+incdir+../../../../project_1.gen/sources_1/ip/ddr4_0/rtl/cal" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/6f8f/hdl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/0127/hdl/verilog" "+incdir+D:/2024_2/Vivado/2024.2/data/xilinx_vip/include" \
"../../../../project_1.gen/sources_1/ip/fifo_32w_8r/sim/fifo_32w_8r.v" \
"../../../../../EnDec_src/Encoder.v" \
"../../../../project_1.srcs/sources_1/imports/imports/gtwizard_ultrascale_0_prbs_any.v" \
"../../../../project_1.srcs/sources_1/new/tlast_generator.v" \
"../../../../project_1.srcs/sources_1/new/tx_chain.v" \
"../../../../project_1.srcs/sim_1/new/loopback_tb.v" \

# compile glbl module
C:\\modeltech64_2020.4\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

