######################################################################
#
# File name : loopback_tb_simulate.do
# Created on: Mon Oct 27 20:06:12 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L xilinx_vip -L xpm -L xbip_utils_v3_0_14 -L axi_utils_v2_0_10 -L c_reg_fd_v12_0_10 -L xbip_dsp48_wrapper_v3_0_6 -L xbip_pipe_v3_0_10 -L c_addsub_v12_0_19 -L c_compare_v12_0_10 -L c_counter_binary_v12_0_20 -L c_shift_ram_v12_0_18 -L mult_gen_v12_0_22 -L rs_toolbox_v9_0_14 -L sid_v8_0_22 -L rs_encoder_v9_0_22 -L fifo_generator_v13_2_11 -L xilinx_vip -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.loopback_tb xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {loopback_tb_wave.do}

view wave
view structure
view signals

do {loopback_tb.udo}

run 1000ns
