######################################################################
#
# File name : loopback_tb_wave.do
# Created on: Mon Oct 27 20:06:12 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
