######################################################################
#
# File name : tb_fec_gth_loopback_top_wave.do
# Created on: Tue Dec 16 16:41:51 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
