######################################################################
#
# File name : tb_fec_rs_chain_intlv_simulate.do
# Created on: Sun Dec 07 22:42:02 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L fifo_generator_v13_2_11 -L xbip_utils_v3_0_14 -L axi_utils_v2_0_10 -L c_reg_fd_v12_0_10 -L xbip_dsp48_wrapper_v3_0_6 -L xbip_pipe_v3_0_10 -L c_addsub_v12_0_19 -L c_counter_binary_v12_0_20 -L c_shift_ram_v12_0_18 -L c_compare_v12_0_10 -L rs_toolbox_v9_0_14 -L rs_decoder_v9_0_23 -L rs_encoder_v9_0_22 -L xilinx_vip -L unisims_ver -L unimacro_ver -L secureip -L xpm -lib xil_defaultlib xil_defaultlib.tb_fec_rs_chain_intlv xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {tb_fec_rs_chain_intlv_wave.do}

view wave
view structure
view signals

log -r /*

do {tb_fec_rs_chain_intlv.udo}

run 0
