######################################################################
#
# File name : tb_fec_rs_chain_intlv_wave.do
# Created on: Sun Dec 07 22:42:02 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
