######################################################################
#
# File name : tb_fec_gth_loopback_top_simulate.do
# Created on: Fri Jan 23 17:15:27 +0800 2026
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -voptargs="+acc=npr" -L xil_defaultlib -L gtwizard_ultrascale_v1_7_19 -L xilinx_vip -L unisims_ver -L unimacro_ver -L secureip -L xpm -lib xil_defaultlib xil_defaultlib.tb_fec_gth_loopback_top xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {tb_fec_gth_loopback_top_wave.do}

view wave
view structure
view signals

log -r /*

do {tb_fec_gth_loopback_top.udo}

# execute post tcl file
set rc [catch {
  puts "source wave nameformat short"
  source "wave nameformat short"
} result]
if {$rc} {
  puts "$result"
  puts "ERROR: \[USF-simtcl-1\] Script failed:wave nameformat short"
}

run 0
