######################################################################
#
# File name : tb_fec_gth_loopback_top_wave.do
# Created on: Fri Jan 23 17:15:27 +0800 2026
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
