######################################################################
#
# File name : tb_fec_rs_chain_intlv_compile.do
# Created on: Sun Dec 07 22:42:01 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
C:\\modeltech64_2020.4\\win64\\vlib modelsim_lib/work
C:\\modeltech64_2020.4\\win64\\vlib modelsim_lib/msim

C:\\modeltech64_2020.4\\win64\\vlib modelsim_lib/msim/xil_defaultlib

C:\\modeltech64_2020.4\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

C:\\modeltech64_2020.4\\win64\\vlog  -mfcu -work xil_defaultlib  "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/6f8f/hdl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/0127/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/ip/ddr4_0/ip_1/rtl/map" "+incdir+../../../../project_1.gen/sources_1/ip/ddr4_0/rtl/ip_top" "+incdir+../../../../project_1.gen/sources_1/ip/ddr4_0/rtl/cal" "+incdir+../../../../project_1.ip_user_files/ipstatic" "+incdir+D:/2024_2/Vivado/2024.2/data/xilinx_vip/include" \
"../../../../project_1.gen/sources_1/ip/dec_fifo_8w_8r/sim/dec_fifo_8w_8r.v" \

C:\\modeltech64_2020.4\\win64\\vcom  -93 -work xil_defaultlib  \
"../../../../project_1.gen/sources_1/ip/rs_decoder_0/sim/rs_decoder_0.vhd" \
"../../../../project_1.gen/sources_1/ip/rs_encoder_0/sim/rs_encoder_0.vhd" \

C:\\modeltech64_2020.4\\win64\\vlog  -mfcu -work xil_defaultlib  "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/6f8f/hdl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/0127/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/ip/ddr4_0/ip_1/rtl/map" "+incdir+../../../../project_1.gen/sources_1/ip/ddr4_0/rtl/ip_top" "+incdir+../../../../project_1.gen/sources_1/ip/ddr4_0/rtl/cal" "+incdir+../../../../project_1.ip_user_files/ipstatic" "+incdir+D:/2024_2/Vivado/2024.2/data/xilinx_vip/include" \
"../../../../project_1.gen/sources_1/ip/fifo_0/sim/fifo_0.v" \
"../../../../project_1.srcs/sim_1/new/AdditiveScrambler.v" \
"../../../../project_1.srcs/sources_1/new/crc32.v" \
"../../../../project_1.srcs/sources_1/new/fifo_8b_flag_sync.v" \
"../../../../project_1.srcs/sources_1/new/fso_deframer.v" \
"../../../../project_1.srcs/sources_1/new/fso_framer.v" \
"../../../../project_1.srcs/sources_1/new/gearbox_32to8.v" \
"../../../../project_1.srcs/sources_1/new/gearbox_8to32_bs.v" \
"../../../../project_1.srcs/sources_1/imports/imports/gtwizard_ultrascale_0_prbs_any.v" \
"../../../../project_1.srcs/sim_1/new/rs_Deinterleaver_xpm.v" \
"../../../../project_1.srcs/sources_1/new/rs_decode_backend.v" \
"../../../../project_1.srcs/sources_1/new/rs_encode_frontend.v" \
"../../../../project_1.srcs/sources_1/new/rs_interleaver_xpm.v" \
"../../../../project_1.srcs/sim_1/new/tb_fec_rs_chain_intlv.v" \

# compile glbl module
C:\\modeltech64_2020.4\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

