######################################################################
#
# File name : tb_fec_gth_loopback_top_simulate.do
# Created on: Tue Dec 16 16:41:51 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -voptargs="+acc=npr" -L xil_defaultlib -L xbip_utils_v3_0_14 -L axi_utils_v2_0_10 -L xbip_pipe_v3_0_10 -L xbip_dsp48_wrapper_v3_0_6 -L mult_gen_v12_0_22 -L floating_point_v7_0_24 -L div_gen_v5_1_23 -L fifo_generator_v13_2_11 -L c_reg_fd_v12_0_10 -L c_addsub_v12_0_19 -L c_counter_binary_v12_0_20 -L c_shift_ram_v12_0_18 -L c_compare_v12_0_10 -L rs_toolbox_v9_0_14 -L rs_decoder_v9_0_23 -L rs_encoder_v9_0_22 -L gtwizard_ultrascale_v1_7_19 -L xilinx_vip -L unisims_ver -L unimacro_ver -L secureip -L xpm -lib xil_defaultlib xil_defaultlib.tb_fec_gth_loopback_top xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {tb_fec_gth_loopback_top_wave.do}

view wave
view structure
view signals

log -r /*

do {tb_fec_gth_loopback_top.udo}

# execute post tcl file
set rc [catch {
  puts "source wave nameformat short"
  source "wave nameformat short"
} result]
if {$rc} {
  puts "$result"
  puts "ERROR: \[USF-simtcl-1\] Script failed:wave nameformat short"
}

run 0
