######################################################################
#
# File name : tb_fec_gth_loopback_top_compile.do
# Created on: Tue Jan 20 11:49:02 +0800 2026
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vcom  -93 -work xil_defaultlib  \
"../../../../project_1.gen/sources_1/ip/rs_decoder_0/sim/rs_decoder_0.vhd" \

vlog  -mfcu -work xil_defaultlib "C:/Users/PC/Desktop/fps/EnDec/project_1/project_1.srcs/sources_1/new/global_defines.vh" "+incdir+../../../../project_1.srcs/sources_1/new" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/6f8f/hdl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/0127/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/ip/ddr4_0/ip_1/rtl/map" "+incdir+../../../../project_1.gen/sources_1/ip/ddr4_0/rtl/ip_top" "+incdir+../../../../project_1.gen/sources_1/ip/ddr4_0/rtl/cal" "+incdir+../../../../project_1.ip_user_files/ipstatic" "+incdir+../../../../project_1.ip_user_files/ipstatic/hdl" "+incdir+D:/2024_2/Vivado/2024.2/data/xilinx_vip/include" \
"../../../../project_1.gen/sources_1/ip/async_fifo_32w_32r/sim/async_fifo_32w_32r.v" \
"../../../../project_1.gen/sources_1/ip/vio_frame_cfg/sim/vio_frame_cfg.v" \

vcom  -93 -work xil_defaultlib  \
"../../../../project_1.gen/sources_1/ip/rs_encoder_0/sim/rs_encoder_0.vhd" \

vlog  -mfcu -work xil_defaultlib "C:/Users/PC/Desktop/fps/EnDec/project_1/project_1.srcs/sources_1/new/global_defines.vh" "+incdir+../../../../project_1.srcs/sources_1/new" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/6f8f/hdl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/0127/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/ip/ddr4_0/ip_1/rtl/map" "+incdir+../../../../project_1.gen/sources_1/ip/ddr4_0/rtl/ip_top" "+incdir+../../../../project_1.gen/sources_1/ip/ddr4_0/rtl/cal" "+incdir+../../../../project_1.ip_user_files/ipstatic" "+incdir+../../../../project_1.ip_user_files/ipstatic/hdl" "+incdir+D:/2024_2/Vivado/2024.2/data/xilinx_vip/include" \
"../../../../project_1.gen/sources_1/ip/fifo_0/sim/fifo_0.v" \
"../../../../project_1.gen/sources_1/ip/gtwizard_ultrascale_0/sim/gtwizard_ultrascale_v1_7_gthe4_channel.v" \
"../../../../project_1.gen/sources_1/ip/gtwizard_ultrascale_0/sim/gtwizard_ultrascale_0_gthe4_channel_wrapper.v" \
"../../../../project_1.gen/sources_1/ip/gtwizard_ultrascale_0/sim/gtwizard_ultrascale_v1_7_gthe4_common.v" \
"../../../../project_1.gen/sources_1/ip/gtwizard_ultrascale_0/sim/gtwizard_ultrascale_0_gthe4_common_wrapper.v" \
"../../../../project_1.gen/sources_1/ip/gtwizard_ultrascale_0/sim/gtwizard_ultrascale_0_gtwizard_gthe4.v" \
"../../../../project_1.gen/sources_1/ip/gtwizard_ultrascale_0/sim/gtwizard_ultrascale_0_gtwizard_top.v" \
"../../../../project_1.gen/sources_1/ip/gtwizard_ultrascale_0/sim/gtwizard_ultrascale_0.v" \
"../../../../project_1.gen/sources_1/ip/vio_2/sim/vio_2.v" \
"../../../../project_1.gen/sources_1/ip/clk_wiz_sys/clk_wiz_sys_clk_wiz.v" \
"../../../../project_1.gen/sources_1/ip/clk_wiz_sys/clk_wiz_sys.v" \
"../../../../project_1.srcs/sim_1/new/AdditiveScrambler.v" \
"../../../../project_1.srcs/sources_1/new/axis_fifo_sync.v" \
"../../../../project_1.srcs/sources_1/new/bit_aligner_ind.v" \
"../../../../project_1.srcs/sources_1/new/crc32.v" \
"../../../../project_1.srcs/sources_1/new/fec_gth_loopback_top_s2.v" \
"../../../../project_1.srcs/sources_1/new/fec_rx_s2.v" \
"../../../../project_1.srcs/sources_1/new/fec_tx_s2.v" \
"../../../../project_1.srcs/sources_1/new/fso_deframer.v" \
"../../../../project_1.srcs/sources_1/new/fso_framer.v" \
"../../../../project_1.srcs/sources_1/new/gearbox_32to8.v" \
"../../../../project_1.srcs/sources_1/new/gearbox_8to32_bs.v" \
"../../../../project_1.srcs/sources_1/new/gth_raw_top.v" \
"../../../../project_1.srcs/sources_1/imports/imports/gtwizard_ultrascale_0_prbs_any.v" \
"../../../../project_1.srcs/sources_1/new/rs_decode_backend.v" \
"../../../../project_1.srcs/sources_1/new/rs_encode_frontend.v" \
"../../../../project_1.srcs/sources_1/new/tb_fec_gth_loopback_top.v" \

# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

