######################################################################
#
# File name : tb_fec_gth_loopback_top_wave.do
# Created on: Tue Jan 20 11:49:03 +0800 2026
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
