# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/PC/Desktop/fps/EnDec/project_1/project_1.srcs/sources_1/ip/dec_fifo_8w_8r/dec_fifo_8w_8r.xci
# IP: The module: 'dec_fifo_8w_8r' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/PC/Desktop/fps/EnDec/project_1/project_1.gen/sources_1/ip/dec_fifo_8w_8r/dec_fifo_8w_8r.xdc
# XDC: The top module name and the constraint reference have the same name: 'dec_fifo_8w_8r'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/PC/Desktop/fps/EnDec/project_1/project_1.gen/sources_1/ip/dec_fifo_8w_8r/dec_fifo_8w_8r_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'dec_fifo_8w_8r'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/PC/Desktop/fps/EnDec/project_1/project_1.gen/sources_1/ip/dec_fifo_8w_8r/dec_fifo_8w_8r_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dec_fifo_8w_8r'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/PC/Desktop/fps/EnDec/project_1/project_1.srcs/sources_1/ip/dec_fifo_8w_8r/dec_fifo_8w_8r.xci
# IP: The module: 'dec_fifo_8w_8r' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/PC/Desktop/fps/EnDec/project_1/project_1.gen/sources_1/ip/dec_fifo_8w_8r/dec_fifo_8w_8r.xdc
# XDC: The top module name and the constraint reference have the same name: 'dec_fifo_8w_8r'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/PC/Desktop/fps/EnDec/project_1/project_1.gen/sources_1/ip/dec_fifo_8w_8r/dec_fifo_8w_8r_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'dec_fifo_8w_8r'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/PC/Desktop/fps/EnDec/project_1/project_1.gen/sources_1/ip/dec_fifo_8w_8r/dec_fifo_8w_8r_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dec_fifo_8w_8r'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
