# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/PC/Desktop/fps/EnDec/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_fso_rx_top_0_0/design_1_fso_rx_top_0_0.xci
# IP: The module: 'design_1_fso_rx_top_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: C:/Users/PC/Desktop/fps/EnDec/project_1/project_1.srcs/sources_1/ip/dec_rx_fifo/dec_rx_fifo.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dec_rx_fifo || ORIG_REF_NAME==dec_rx_fifo} -quiet] -quiet

# IP: C:/Users/PC/Desktop/fps/EnDec/project_1/project_1.srcs/sources_1/ip/async_fifo_32w_32r/async_fifo_32w_32r.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==async_fifo_32w_32r || ORIG_REF_NAME==async_fifo_32w_32r} -quiet] -quiet

# IP: C:/Users/PC/Desktop/fps/EnDec/project_1/project_1.srcs/sources_1/ip/gtwizard_ultrascale_0/gtwizard_ultrascale_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==gtwizard_ultrascale_0 || ORIG_REF_NAME==gtwizard_ultrascale_0} -quiet] -quiet

# IP: C:/Users/PC/Desktop/fps/EnDec/project_1/project_1.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet

# IP: C:/Users/PC/Desktop/fps/EnDec/project_1/project_1.srcs/sources_1/ip/dec_fifo_8w_8r/dec_fifo_8w_8r.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dec_fifo_8w_8r || ORIG_REF_NAME==dec_fifo_8w_8r} -quiet] -quiet

# IP: C:/Users/PC/Desktop/fps/EnDec/project_1/project_1.srcs/sources_1/ip/rs_decoder_0/rs_decoder_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rs_decoder_0 || ORIG_REF_NAME==rs_decoder_0} -quiet] -quiet

# XDC: c:/Users/PC/Desktop/fps/EnDec/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_fso_rx_top_0_0/design_1_fso_rx_top_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_fso_rx_top_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/PC/Desktop/fps/EnDec/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_fso_rx_top_0_0/design_1_fso_rx_top_0_0.xci
# IP: The module: 'design_1_fso_rx_top_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: C:/Users/PC/Desktop/fps/EnDec/project_1/project_1.srcs/sources_1/ip/dec_rx_fifo/dec_rx_fifo.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dec_rx_fifo || ORIG_REF_NAME==dec_rx_fifo} -quiet] -quiet

# IP: C:/Users/PC/Desktop/fps/EnDec/project_1/project_1.srcs/sources_1/ip/async_fifo_32w_32r/async_fifo_32w_32r.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==async_fifo_32w_32r || ORIG_REF_NAME==async_fifo_32w_32r} -quiet] -quiet

# IP: C:/Users/PC/Desktop/fps/EnDec/project_1/project_1.srcs/sources_1/ip/gtwizard_ultrascale_0/gtwizard_ultrascale_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==gtwizard_ultrascale_0 || ORIG_REF_NAME==gtwizard_ultrascale_0} -quiet] -quiet

# IP: C:/Users/PC/Desktop/fps/EnDec/project_1/project_1.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet

# IP: C:/Users/PC/Desktop/fps/EnDec/project_1/project_1.srcs/sources_1/ip/dec_fifo_8w_8r/dec_fifo_8w_8r.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dec_fifo_8w_8r || ORIG_REF_NAME==dec_fifo_8w_8r} -quiet] -quiet

# IP: C:/Users/PC/Desktop/fps/EnDec/project_1/project_1.srcs/sources_1/ip/rs_decoder_0/rs_decoder_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rs_decoder_0 || ORIG_REF_NAME==rs_decoder_0} -quiet] -quiet

# XDC: c:/Users/PC/Desktop/fps/EnDec/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_fso_rx_top_0_0/design_1_fso_rx_top_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_fso_rx_top_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
