# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/PC/Desktop/fps/EnDec/project_1/project_1.srcs/sources_1/ip/dec_rx_fifo/dec_rx_fifo.xci
# IP: The module: 'dec_rx_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/PC/Desktop/fps/EnDec/project_1/project_1.gen/sources_1/ip/dec_rx_fifo/dec_rx_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'dec_rx_fifo'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/PC/Desktop/fps/EnDec/project_1/project_1.gen/sources_1/ip/dec_rx_fifo/dec_rx_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'dec_rx_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/PC/Desktop/fps/EnDec/project_1/project_1.gen/sources_1/ip/dec_rx_fifo/dec_rx_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dec_rx_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/PC/Desktop/fps/EnDec/project_1/project_1.srcs/sources_1/ip/dec_rx_fifo/dec_rx_fifo.xci
# IP: The module: 'dec_rx_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/PC/Desktop/fps/EnDec/project_1/project_1.gen/sources_1/ip/dec_rx_fifo/dec_rx_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'dec_rx_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/PC/Desktop/fps/EnDec/project_1/project_1.gen/sources_1/ip/dec_rx_fifo/dec_rx_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'dec_rx_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/PC/Desktop/fps/EnDec/project_1/project_1.gen/sources_1/ip/dec_rx_fifo/dec_rx_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dec_rx_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
