# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/PC/Desktop/fps/EnDec/project_1/project_1.srcs/sources_1/ip/GT_rx500M_tx1G/GT_rx500M_tx1G.xci
# IP: The module: 'GT_rx500M_tx1G' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/PC/Desktop/fps/EnDec/project_1/project_1.gen/sources_1/ip/GT_rx500M_tx1G/synth/GT_rx500M_tx1G_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'GT_rx500M_tx1G'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/PC/Desktop/fps/EnDec/project_1/project_1.gen/sources_1/ip/GT_rx500M_tx1G/synth/GT_rx500M_tx1G.xdc
# XDC: The top module name and the constraint reference have the same name: 'GT_rx500M_tx1G'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/PC/Desktop/fps/EnDec/project_1/project_1.srcs/sources_1/ip/GT_rx500M_tx1G/GT_rx500M_tx1G.xci
# IP: The module: 'GT_rx500M_tx1G' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/PC/Desktop/fps/EnDec/project_1/project_1.gen/sources_1/ip/GT_rx500M_tx1G/synth/GT_rx500M_tx1G_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'GT_rx500M_tx1G'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/PC/Desktop/fps/EnDec/project_1/project_1.gen/sources_1/ip/GT_rx500M_tx1G/synth/GT_rx500M_tx1G.xdc
# XDC: The top module name and the constraint reference have the same name: 'GT_rx500M_tx1G'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
