# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/PC/Desktop/fps/EnDec/project_1/project_1.srcs/sources_1/ip/ibert_ultrascale_gth_0/ibert_ultrascale_gth_0.xci
# IP: The module: 'ibert_ultrascale_gth_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/PC/Desktop/fps/EnDec/project_1/project_1.gen/sources_1/ip/ibert_ultrascale_gth_0/synth/ibert_waivers.xdc
# XDC: The top module name and the constraint reference have the same name: 'ibert_ultrascale_gth_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/PC/Desktop/fps/EnDec/project_1/project_1.gen/sources_1/ip/ibert_ultrascale_gth_0/synth/ibert_ultrascale_gth_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ibert_ultrascale_gth_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/PC/Desktop/fps/EnDec/project_1/project_1.gen/sources_1/ip/ibert_ultrascale_gth_0/synth/ibert_ultrascale_gth_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ibert_ultrascale_gth_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/PC/Desktop/fps/EnDec/project_1/project_1.gen/sources_1/ip/ibert_ultrascale_gth_0/synth/sw_mcs_all.xdc
# XDC: The top module name and the constraint reference have the same name: 'ibert_ultrascale_gth_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/PC/Desktop/fps/EnDec/project_1/project_1.gen/sources_1/ip/ibert_ultrascale_gth_0/synth/attributes.xdc
# XDC: The top module name and the constraint reference have the same name: 'ibert_ultrascale_gth_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/PC/Desktop/fps/EnDec/project_1/project_1.srcs/sources_1/ip/ibert_ultrascale_gth_0/ibert_ultrascale_gth_0.xci
# IP: The module: 'ibert_ultrascale_gth_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/PC/Desktop/fps/EnDec/project_1/project_1.gen/sources_1/ip/ibert_ultrascale_gth_0/synth/ibert_waivers.xdc
# XDC: The top module name and the constraint reference have the same name: 'ibert_ultrascale_gth_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/PC/Desktop/fps/EnDec/project_1/project_1.gen/sources_1/ip/ibert_ultrascale_gth_0/synth/ibert_ultrascale_gth_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ibert_ultrascale_gth_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/PC/Desktop/fps/EnDec/project_1/project_1.gen/sources_1/ip/ibert_ultrascale_gth_0/synth/ibert_ultrascale_gth_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ibert_ultrascale_gth_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/PC/Desktop/fps/EnDec/project_1/project_1.gen/sources_1/ip/ibert_ultrascale_gth_0/synth/sw_mcs_all.xdc
# XDC: The top module name and the constraint reference have the same name: 'ibert_ultrascale_gth_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/PC/Desktop/fps/EnDec/project_1/project_1.gen/sources_1/ip/ibert_ultrascale_gth_0/synth/attributes.xdc
# XDC: The top module name and the constraint reference have the same name: 'ibert_ultrascale_gth_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
