# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/PC/Desktop/fps/EnDec/project_1/project_1.srcs/sources_1/ip/sid_0/sid_0.xci
# IP: The module: 'sid_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/PC/Desktop/fps/EnDec/project_1/project_1.gen/sources_1/ip/sid_0/sid_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sid_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/PC/Desktop/fps/EnDec/project_1/project_1.srcs/sources_1/ip/sid_0/sid_0.xci
# IP: The module: 'sid_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/PC/Desktop/fps/EnDec/project_1/project_1.gen/sources_1/ip/sid_0/sid_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sid_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
